# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegionProposed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegionProposed.proto',
  package='wvtlicenseplate',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14RegionProposed.proto\x12\x0fwvtlicenseplate\"\x18\n\ttestInput\x12\x0b\n\x03\x61\x62\x63\x18\x01 \x01(\t\"\x19\n\nTestOutput\x12\x0b\n\x03xyz\x18\x01 \x01(\t\"!\n\x0cInputFileMp4\x12\x11\n\tInputFile\x18\x01 \x01(\x0c\"t\n\x10IdentifiedObject\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x12\x0f\n\x07\x43lassId\x18\x05 \x01(\x05\x12\x10\n\x08ObjectId\x18\x06 \x01(\x05\x12\r\n\x05Label\x18\x07 \x01(\t\"c\n\x0e\x44\x65tectionFrame\x12\x13\n\x0b\x46rameNumber\x18\x01 \x01(\x05\x12<\n\x11IdentificationObj\x18\x02 \x03(\x0b\x32!.wvtlicenseplate.IdentifiedObject2\xa8\x01\n\x0eRegionProposed\x12R\n\x0eProcessMp4File\x12\x1d.wvtlicenseplate.InputFileMp4\x1a\x1f.wvtlicenseplate.DetectionFrame0\x01\x12\x42\n\x07TestMet\x12\x1a.wvtlicenseplate.testInput\x1a\x1b.wvtlicenseplate.TestOutputb\x06proto3'
)




_TESTINPUT = _descriptor.Descriptor(
  name='testInput',
  full_name='wvtlicenseplate.testInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='abc', full_name='wvtlicenseplate.testInput.abc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=65,
)


_TESTOUTPUT = _descriptor.Descriptor(
  name='TestOutput',
  full_name='wvtlicenseplate.TestOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xyz', full_name='wvtlicenseplate.TestOutput.xyz', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=92,
)


_INPUTFILEMP4 = _descriptor.Descriptor(
  name='InputFileMp4',
  full_name='wvtlicenseplate.InputFileMp4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='InputFile', full_name='wvtlicenseplate.InputFileMp4.InputFile', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=127,
)


_IDENTIFIEDOBJECT = _descriptor.Descriptor(
  name='IdentifiedObject',
  full_name='wvtlicenseplate.IdentifiedObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='wvtlicenseplate.IdentifiedObject.x1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y1', full_name='wvtlicenseplate.IdentifiedObject.y1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x2', full_name='wvtlicenseplate.IdentifiedObject.x2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y2', full_name='wvtlicenseplate.IdentifiedObject.y2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ClassId', full_name='wvtlicenseplate.IdentifiedObject.ClassId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectId', full_name='wvtlicenseplate.IdentifiedObject.ObjectId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Label', full_name='wvtlicenseplate.IdentifiedObject.Label', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=245,
)


_DETECTIONFRAME = _descriptor.Descriptor(
  name='DetectionFrame',
  full_name='wvtlicenseplate.DetectionFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='FrameNumber', full_name='wvtlicenseplate.DetectionFrame.FrameNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='IdentificationObj', full_name='wvtlicenseplate.DetectionFrame.IdentificationObj', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=346,
)

_DETECTIONFRAME.fields_by_name['IdentificationObj'].message_type = _IDENTIFIEDOBJECT
DESCRIPTOR.message_types_by_name['testInput'] = _TESTINPUT
DESCRIPTOR.message_types_by_name['TestOutput'] = _TESTOUTPUT
DESCRIPTOR.message_types_by_name['InputFileMp4'] = _INPUTFILEMP4
DESCRIPTOR.message_types_by_name['IdentifiedObject'] = _IDENTIFIEDOBJECT
DESCRIPTOR.message_types_by_name['DetectionFrame'] = _DETECTIONFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

testInput = _reflection.GeneratedProtocolMessageType('testInput', (_message.Message,), {
  'DESCRIPTOR' : _TESTINPUT,
  '__module__' : 'RegionProposed_pb2'
  # @@protoc_insertion_point(class_scope:wvtlicenseplate.testInput)
  })
_sym_db.RegisterMessage(testInput)

TestOutput = _reflection.GeneratedProtocolMessageType('TestOutput', (_message.Message,), {
  'DESCRIPTOR' : _TESTOUTPUT,
  '__module__' : 'RegionProposed_pb2'
  # @@protoc_insertion_point(class_scope:wvtlicenseplate.TestOutput)
  })
_sym_db.RegisterMessage(TestOutput)

InputFileMp4 = _reflection.GeneratedProtocolMessageType('InputFileMp4', (_message.Message,), {
  'DESCRIPTOR' : _INPUTFILEMP4,
  '__module__' : 'RegionProposed_pb2'
  # @@protoc_insertion_point(class_scope:wvtlicenseplate.InputFileMp4)
  })
_sym_db.RegisterMessage(InputFileMp4)

IdentifiedObject = _reflection.GeneratedProtocolMessageType('IdentifiedObject', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFIEDOBJECT,
  '__module__' : 'RegionProposed_pb2'
  # @@protoc_insertion_point(class_scope:wvtlicenseplate.IdentifiedObject)
  })
_sym_db.RegisterMessage(IdentifiedObject)

DetectionFrame = _reflection.GeneratedProtocolMessageType('DetectionFrame', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONFRAME,
  '__module__' : 'RegionProposed_pb2'
  # @@protoc_insertion_point(class_scope:wvtlicenseplate.DetectionFrame)
  })
_sym_db.RegisterMessage(DetectionFrame)



_REGIONPROPOSED = _descriptor.ServiceDescriptor(
  name='RegionProposed',
  full_name='wvtlicenseplate.RegionProposed',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=349,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessMp4File',
    full_name='wvtlicenseplate.RegionProposed.ProcessMp4File',
    index=0,
    containing_service=None,
    input_type=_INPUTFILEMP4,
    output_type=_DETECTIONFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestMet',
    full_name='wvtlicenseplate.RegionProposed.TestMet',
    index=1,
    containing_service=None,
    input_type=_TESTINPUT,
    output_type=_TESTOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGIONPROPOSED)

DESCRIPTOR.services_by_name['RegionProposed'] = _REGIONPROPOSED

# @@protoc_insertion_point(module_scope)
